version: 1
disable_existing_loggers: False
formatters:
  full:
    format: '%(asctime)s %(name)s %(filename)s:%(lineno)d | %(levelname)s | %(message)s'
  simple:
    format: '%(levelname)s | %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: full
    filename: /var/log/llamas.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  FlaskFatLog:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: false

root:
    handlers: [console, file_handler]
